c++: Error diagnostics for pointer-to-member type [PR38612]
Consider the following pr38612.cc file:
--

struct Base {};
struct X;                       // X derived from Base later but incomplete here
struct Y {};                    // Y not derived from Base

int test1(int Base::* p2m, X* object)
{
    return object->*p2m;        // fails because X is incomplete
}

struct X : Base
{
};

int test2(int Base::* p2m, X* object)
{
    return object->*p2m;        // OK
}

int test3(int Base::* p2m, Y* object)
{
    return object->*p2m;        // fails because Y is not derived from Base
}

--

Now for test1 and test3 it produces the following errors:

pr38612.cc: In function 'int test1(int Base::*, X*)':
pr38612.cc:8:21: error: pointer to member type 'int' incompatible \
with incomplete object type 'X'
    8 |     return object->*p2m;        // fails because X is incomplete
      |                     ^~~
pr38612.cc: In function 'int test3(int Base::*, Y*)':
pr38612.cc:22:21: error: pointer to member type 'int' incompatible \
with object type 'Y' because 'Y' is not derived from 'Base'
   22 |     return object->*p2m;        // fails because Y is not derived \
from Base
      |                     ^~~

Signed-off-by: Alex Yesmanchyk <aliaksandr.yesmanchyk@gmail.com>